# Book settings
title: Python numérique
author: Thierry Parmentelat
logo: media/logo-python.svg

only_build_toc_files: true

execute:
  execute_notebooks: force

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent

repository:
  url: https://github.com/ue12/python-numerique
  branch: master
  path_to_book: notebooks

html:
  use_repository_button: yes
  use_edit_page_button: yes
  use_issues_button: yes

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image
