name: docs
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Activate conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: python-numérique
          environment-file: environment.yml

      - name: Build the documentation
        run: cd notebooks && make

      - name: Prepare deployment
        run: rm .gitignore && cp -rf notebooks/_build docs

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "."
          SINGLE_COMMIT: true
          PRESERVE: true