name: docs
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the tepository
        uses: actions/checkout@v2

      - name: Build the documentation
        run: cd notebooks & make & cp -rf _build ../docs

      - name: Prepare deployment
        run: rm .gitignore

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "."
          SINGLE_COMMIT: true
          PRESERVE: true